export const languages = [
    {
        name: "HTML",
        backgroundColor: "#ffea00",
        backgroundColorBottom: "#ff8800",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#ffa200",
        backgroundColorThree: "#ffdd00",
        color: "#B65409",
    },
    {
        name: "CSS",
        backgroundColor: "#caf0f8",
        backgroundColorBottom: "#0096c7",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#48cae4",
        backgroundColorThree: "#ade8f4",
        color: "#007D96",
    },
    {
        name: "JavaScript",
        backgroundColor: "#ffff3f",
        backgroundColorBottom: "#80b918",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#d4d700",
        backgroundColorThree: "#eeef20",
        color: "#846700",
    },
    {
        name: "React",
        backgroundColor: "#dec9e9",
        backgroundColorBottom: "#9163cb",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#b185db",
        backgroundColorThree: "#d2b7e5",
        color: "#6A00B6",
    },
    {
        name: "TypeScript",
        backgroundColor: "#90e0ef",
        backgroundColorBottom: "#0077b6",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#0077b6",
        backgroundColorThree: "#00b4d8",
        color: "#F6FDFF",
    },
    {
        name: "Node.js",
        backgroundColor: "#e9ecef",
        backgroundColorBottom: "#343a40",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#6c757d",
        backgroundColorThree: "#dee2e6",
        color: "#565656",
    },
    {
        name: "Python",
        backgroundColor: "#e4b1ab",
        backgroundColorBottom: "#cc444b",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#da5552",
        backgroundColorThree: "#e39695",
        color: "#FFFFFF",
    },
    {
        name: "Ruby",
        backgroundColor: "#aec3b0",
        backgroundColorBottom: "#1d2d44",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#3e5c76",
        backgroundColorThree: "#748cab",
        color: "#f7f7f7",
    },
    {
        name: "Assembly",
        backgroundColor: "#ffdab9",
        backgroundColorBottom: "#f08080",
        backgroundColorTwo: "#ffffff",
        backgroundColorTwoBottom: "#f4978e",
        backgroundColorThree: "#fbc4ab",
        color: "#A43400",
    },
]

export const wordsList = [
    "apple", "bench", "brave", "candy", "dream", "eagle", "flour", "giant", "house", "jolly",
    "knife", "lemon", "mango", "novel", "ocean", "paint", "queen", "river", "smart", "table",
    "uncle", "vital", "world", "xylog", "zebra", "bamboo", "castle", "daring", "energy", "famous",
    "garden", "handle", "ignore", "jigsaw", "kidney", "lantern", "mentor", "notice", "oracle", "pencil",
    "quartz", "ribbon", "safety", "tunnel", "unique", "vacuum", "wealth", "xenons", "yellow", "zephyr",
    "ability", "balance", "courage", "dynamic", "explore", "fortune", "general", "harvest", "imagine", "journey",
    "kingdom", "liberty", "mystery", "network", "outlook", "passion", "quality", "respect", "sincere", "thunder",
    "ultimate", "variety", "welcome", "xylitol", "yawning", "zealous", "amazing", "breathe", "compact", "daylight",
    "elegant", "fantasy", "gateway", "horizon", "insight", "justice", "knotted", "landing", "morning", "nostalgic",
    "opinion", "pioneer", "quietly", "radical", "sunrise", "tourism", "utility", "victory", "warrior", "yanking",
    "alpine", "barrel", "citrus", "deluxe", "esteem", "fridge", "glance", "hunger", "impact", "jockey",
    "kitten", "laptop", "marble", "notion", "oxygen", "puzzle", "quiver", "rescue", "sizzle", "tundra",
    "upbeat", "voyage", "wisdom", "xylene", "yonder", "zenith", "archive", "bizarre", "concert", "defense",
    "embrace", "formula", "gravity", "harmony", "insider", "justice", "kingpin", "leisure", "monster", "nursery",
    "octagon", "painter", "quantum", "rebuild", "scenery", "tangent", "undergo", "vintage", "warfare", "yelling",
    "artwork", "backing", "charity", "drought", "edition", "fragile", "garment", "habitat", "isolate", "jumbled",
    "kindred", "laundry", "mystify", "neutron", "observe", "payroll", "quickly", "reflect", "sailing", "terrain",
    "unravel", "venture", "whisper", "xylitol", "yearned", "zigzags", "arrival", "battery", "courage", "daytime",
    "emotion", "fortune", "general", "history", "imagery", "journal", "kingdom", "leather", "mystery", "natural",
    "outlook", "private", "quieter", "respect", "sincere", "thought", "upgrade", "visible", "willing", "yellowish",
    "absolve", "banquet", "cascade", "dolphin", "eclipse", "furnish", "glimpse", "highway", "impress", "junction",
    "kinetic", "lanolin", "miracle", "nebular", "optical", "picture", "qualify", "recycle", "scenery", "tourist",
    "unravel", "vibrant", "wealthy", "xylitol", "yawning", "zealots", "algebra", "baggage", "charmer", "drizzle",
    "elastic", "flaming", "griddle", "habitat", "iceberg", "jiggled", "kitchen", "library", "musical", "natural",
    "outcome", "perfect", "quarter", "railway", "serpent", "truffle", "unicorn", "venture", "whistle", "xylitol",
    "yardage", "zealous", "amnesty", "balance", "concise", "density", "elegant", "fateful", "gateway", "highway",
    "impress", "justice", "kidneys", "lingual", "mystery", "notably", "outlook", "postage", "qualify", "rebound",
    "sincere", "tangible", "upgrade", "visible", "weaving", "yanking", "zealots", "amnesia", "bargain", "concert",
    "dynamic", "elastic", "fragile", "glisten", "harvest", "iceberg", "journey", "kingpin", "library", "musical",
    "neutron", "opulent", "perfect", "quarter", "radical", "serpent", "thought", "unravel", "vintage", "willing"
]